# Generated by Django 3.0 on 2020-06-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20200520_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='massage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mass', models.TextField(max_length=200)),
            ],
        ),
    ]
