# Generated by Django 3.0 on 2020-06-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_massage_emai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='mass',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='massage',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
