# Generated by Django 3.0 on 2020-06-13 05:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_auto_20200611_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='massage',
            old_name='emai',
            new_name='email',
        ),
        migrations.AddField(
            model_name='massage',
            name='subjects',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
