# Generated by Django 3.0 on 2020-06-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_auto_20200613_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='subjects',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
