# Generated by Django 3.0 on 2020-06-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_auto_20200613_0535'),
    ]

    operations = [
        migrations.CreateModel(
            name='footer_Massage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=80)),
                ('text', models.TextField()),
            ],
        ),
    ]
