# Generated by Django 3.0 on 2020-06-16 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_footer_massage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer_massage',
            old_name='text',
            new_name='tolk',
        ),
    ]
